# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT
# Mod Properties
mod_version=1.0.2
maven_group=com.mossshade
archives_base_name=soullink
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.145.3+26.1.1

java_version=25

# Resource pack properties
pack_format=15
pack_min_format=15
pack_max_format=84
pack_supported_formats=15,64

org.gradle.configuration-cache=false